services:
  mysql:
    container_name: biblia-mysql
    image: 'mysql:8.0'
    working_dir: /var/www/html
    restart: always
    volumes:
      - './:/var/www/html'
      - './.docker/mysql/data:/var/lib/mysql'
      - './.docker/mysql_dumps:/docker-entrypoint-initdb.d'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password

  phpmyadmin:
    container_name: biblia-php_my_admin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80

    environment:
      - PMA_ARBITRARY=1